### ISSUE TITLE
能正常登录，有点小问题，Chromium残留在内存中

### ISSUE THREAD

**Issue by ZengOwen** [AwesomeCrawler/taobao_login#1]
另外，为何登录pub.alimama.com不成功

**Comment by MemoryAndDream** [comment]
> 另外，为何登录pub.alimama.com不成功

我这是可以的，不过不能无头登录，二是 browser = await launch({'headless': False, 'args': ['--no-sandbox'],'dumpio':True}) 最后这个参数要加上

**Comment by zhangslob** [comment]
可以自行添加 `browser.close()` 方法
