### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by ahyangnb** [AwesomeCrawler/taobao_login#4]

**Comment by ahyangnb** [comment]
q1deMacBook-Pro:taobao_login-master q1$ python taobao_login.py 
  File "taobao_login.py", line 17
    async def taobao_login(username, password, url):
            ^
SyntaxError: invalid syntax

**Comment by ahyangnb** [comment]
本人是新手

**Comment by VidocqH** [comment]
用更高的python版本

**Comment by ahyangnb** [comment]
thx
